# =========================================================
#  LangFlow Template Configuration: Notion → LLM → Slack
# =========================================================
template:
  name: "notion-slack-summary"
  version: "1.0.0"
  description: "A LangFlow template that queries tasks from Notion, summarizes them using an LLM, and sends results to Slack."
  author: "Marcus Izumi"
  category: "Collaboration"
  complexity: "Intermediate"

# ---------------------------------------------------------
# Environment Variables (required for runtime)
# ---------------------------------------------------------
globals:
  env_required:
    - OPENAI_API_KEY        # Used by LLM component
    - NOTION_SECRET         # Used by Notion API
    - NOTION_DATABASE_ID    # Your Notion tasks database
    - SLACK_USER_TOKEN      # For Slack user authentication

# ---------------------------------------------------------
# Service Configuration
# ---------------------------------------------------------
services:

  notion:
    base_url: "https://api.notion.com/v1"
    version: "2022-06-28"
    description: "Access tasks and project data from Notion"
    default_database_env: "NOTION_DATABASE_ID"
    endpoints:
      query_database: "/databases/{database_id}/query"

  openai:
    base_url: "https://api.openai.com/v1"
    model_default: "gpt-4o-mini"
    description: "LLM used to interpret and summarize task data"

  slack:
    base_url: "https://slack.com/api"
    post_message_endpoint: "chat.postMessage"
    description: "Used to send summary updates to a Slack channel"

# ---------------------------------------------------------
# Components and Behavior
# ---------------------------------------------------------
components:

  notion_query_builder:
    type: "custom"
    file: "components/notion_query_builder.py"
    description: "Converts natural language into a valid Notion database query JSON"
    inputs:
      - "User Query (string)"
    outputs:
      - "Query JSON (Message)"
    parameters:
      default_filters:
        - property: "Status"
          condition: "equals"
          value: "In Progress"
      max_page_size: 10

  llm_summarizer:
    type: "model"
    provider: "OpenAI"
    model_name: "gpt-4o-mini"
    temperature: 0.3
    description: "Summarizes the filtered Notion tasks into a natural Slack message"

  slack_sender:
    type: "custom"
    file: "components/slack_user_sender.py"
    description: "Posts a message to Slack as a user"
    parameters:
      default_channel: "#project-updates"
      icon_emoji: ":memo:"
      username: "Task Summarizer Bot"

# ---------------------------------------------------------
# Execution Flow
# ---------------------------------------------------------
flow:
  steps:
    - id: "step_1"
      name: "Build Notion Query"
      component: "notion_query_builder"
      next: "step_2"

    - id: "step_2"
      name: "Summarize via LLM"
      component: "llm_summarizer"
      next: "step_3"

    - id: "step_3"
      name: "Send to Slack"
      component: "slack_sender"
      next: null

# ---------------------------------------------------------
# Output Settings
# ---------------------------------------------------------
output:
  format: "Message"
  include_status: true
  include_metadata: true

# ---------------------------------------------------------
# Error Handling
# ---------------------------------------------------------
error_handling:
  retry_attempts: 3
  timeout_seconds: 30
  messages:
    network_error: "Network connectivity issue — please retry."
    invalid_response: "Unexpected response from Notion or Slack API."
    missing_env: "One or more required environment variables are missing."

# ---------------------------------------------------------
# Performance
# ---------------------------------------------------------
performance:
  cache_enabled: false
  request_delay: 0.1
  max_concurrent_requests: 5
