# Perplexity Academic Model Component Configuration
template:
  name: "perplexity-academic-model"
  version: "1.3.0"
  description: "LangFlow component for Perplexity API with academic search capabilities"
  author: "PREAA Templates Team"

# Perplexity API Configuration
perplexity:
  api_url: "https://api.perplexity.ai/chat/completions"
  timeout: 60
  max_retries: 3
  
  # Available models
  models:
    sonar:
      description: "General purpose model with web search"
      max_tokens: 4096
      supports_search: true
      
    sonar-pro:
      description: "Enhanced model with better reasoning"
      max_tokens: 4096
      supports_search: true
      
    sonar-reasoning:
      description: "Advanced reasoning capabilities"
      max_tokens: 4096
      supports_search: true

# Search Configuration
search:
  modes:
    default:
      description: "General web search"
      academic_priority: false
      
    academic:
      description: "Academic sources only (peer-reviewed papers, scholarly sources)"
      academic_priority: true
      preferred_domains:
        - "arxiv.org"
        - "ieee.org"
        - "nature.com"
        - "science.org"
        - "pubmed.ncbi.nlm.nih.gov"
        - "scholar.google.com"
        - "academia.edu"
        - "researchgate.net"
  
  # Domain filtering examples
  domain_filters:
    academic_only:
      include:
        - "arxiv.org"
        - "ieee.org"
        - "nature.com"
        - "science.org"
        - "pubmed.ncbi.nlm.nih.gov"
        - "scholar.google.com"
        - "academia.edu"
        - "researchgate.net"
        - "jstor.org"
        - "springer.com"
        - "elsevier.com"
        - "wiley.com"
        - "tandfonline.com"
      
    reliable_sources:
      include:
        - "wikipedia.org"
        - "britannica.com"
        - "gov.uk"
        - "gov.au"
        - "nasa.gov"
        - "nih.gov"
        - "cdc.gov"
        - "who.int"
        - "un.org"
        - "oecd.org"
      
    exclude_social:
      exclude:
        - "reddit.com"
        - "twitter.com"
        - "facebook.com"
        - "instagram.com"
        - "tiktok.com"
        - "youtube.com"
        - "linkedin.com"
  
  # Recency filters
  recency_filters:
    very_recent: "hour"
    recent: "day"
    this_week: "week"
    this_month: "month"
    this_year: "year"

# Model Parameters
model_parameters:
  temperature:
    default: 0.7
    range: [0.0, 2.0]
    step: 0.1
    description: "Controls randomness in generation"
    
  top_p:
    default: 0.9
    range: [0.0, 1.0]
    step: 0.01
    description: "Nucleus sampling parameter"
    
  top_k:
    default: 0
    range: [0, 100]
    step: 1
    description: "Top-k sampling parameter (0 to disable)"
    
  max_tokens:
    default: 1024
    range: [1, 4096]
    step: 1
    description: "Maximum number of tokens to generate"
    
  presence_penalty:
    default: 0.0
    range: [-2.0, 2.0]
    step: 0.1
    description: "Penalizes new tokens based on whether they appear in the text so far"
    
  frequency_penalty:
    default: 0.0
    range: [-2.0, 2.0]
    step: 0.1
    description: "Penalizes new tokens based on their frequency in the text so far"

# Output Configuration
output:
  citations:
    enabled: true
    format_as_links: true
    include_metadata: true
    
  related_questions:
    enabled: false
    max_questions: 5
    
  images:
    enabled: false
    max_images: 10
    
  metadata:
    include_usage_stats: true
    include_search_params: true
    include_model_info: true

# Citation Formatting
citations:
  academic_mode_indicator: "📖 Academic sources prioritized"
  sources_header: "📚 Sources"
  related_questions_header: "💡 Related Questions"
  images_header: "🖼️ Related Images"
  
  # Domain-specific formatting
  domain_titles:
    "wikipedia.org": "Wikipedia"
    "arxiv.org": "arXiv"
    "github.com": "GitHub"
    "stackoverflow.com": "StackOverflow"
    "nature.com": "Nature"
    "science.org": "Science"
    "ieee.org": "IEEE"
    "pubmed.ncbi.nlm.nih.gov": "PubMed"
    "scholar.google.com": "Google Scholar"
    "academia.edu": "Academia.edu"
    "researchgate.net": "ResearchGate"
    "jstor.org": "JSTOR"
    "springer.com": "Springer"
    "elsevier.com": "Elsevier"
    "wiley.com": "Wiley"
    "tandfonline.com": "Taylor & Francis"

# Error Handling
error_handling:
  retry_attempts: 3
  retry_delay: 1.0  # seconds
  timeout: 60.0  # seconds
  
  # Error messages
  messages:
    api_key_invalid: "Invalid or expired Perplexity API key"
    rate_limit_exceeded: "API rate limit exceeded. Please try again later"
    network_error: "Network error occurred. Please check your connection"
    timeout_error: "Request timed out. Please try again"
    invalid_response: "Invalid response from Perplexity API"
    no_input: "No input message provided"

# Performance Optimization
performance:
  cache_enabled: false
  cache_duration: 3600  # seconds
  max_concurrent_requests: 5
  request_delay: 0.1  # seconds between requests
  
# Security
security:
  api_key_validation: true
  input_sanitization: true
  output_filtering: true
  rate_limiting: true
  max_requests_per_minute: 60
