# Composio Connect Component Configuration
template:
  name: "composio-connect"
  version: "1.3.0"
  description: "LangFlow component for Composio marketplace integration with 200+ tools"
  author: "PREAA Templates Team"

# Composio API Configuration
composio:
  api_url: "https://api.composio.dev"
  timeout: 60
  max_retries: 3
  
  # Authentication
  authentication:
    type: "api_key"
    required: true
    description: "Composio API key for authentication"

# Supported Integrations
integrations:
  productivity:
    microsoft_365:
      name: "Microsoft 365"
      description: "Outlook, Teams, OneDrive, SharePoint"
      authentication: "oauth2"
      actions:
        - "send_email"
        - "list_messages"
        - "create_calendar_event"
        - "reply_to_email"
        - "upload_file"
        - "create_team_channel"
      
    google_workspace:
      name: "Google Workspace"
      description: "Gmail, Calendar, Drive, Docs, Sheets"
      authentication: "oauth2"
      actions:
        - "gmail_send"
        - "calendar_list_events"
        - "drive_upload_file"
        - "docs_create"
        - "sheets_create"
      
    slack:
      name: "Slack"
      description: "Messaging, file sharing, workflow automation"
      authentication: "oauth2"
      actions:
        - "send_message"
        - "create_channel"
        - "upload_file"
        - "schedule_message"
      
    discord:
      name: "Discord"
      description: "Community management, bot interactions"
      authentication: "oauth2"
      actions:
        - "send_message"
        - "create_thread"
        - "manage_roles"
        - "moderate_content"

  development:
    github:
      name: "GitHub"
      description: "Repository management, issues, pull requests"
      authentication: "oauth2"
      actions:
        - "create_repository"
        - "create_issue"
        - "create_pull_request"
        - "list_commits"
        - "manage_branches"
      
    gitlab:
      name: "GitLab"
      description: "CI/CD, project management"
      authentication: "oauth2"
      actions:
        - "create_project"
        - "run_pipeline"
        - "manage_merge_requests"
        - "create_issue"
      
    jira:
      name: "Jira"
      description: "Issue tracking, project management"
      authentication: "oauth2"
      actions:
        - "create_issue"
        - "update_issue"
        - "search_issues"
        - "create_project"

  data_analytics:
    notion:
      name: "Notion"
      description: "Database management, documentation"
      authentication: "oauth2"
      actions:
        - "create_page"
        - "update_database"
        - "search_pages"
        - "create_database"
      
    airtable:
      name: "Airtable"
      description: "Spreadsheet-database hybrid"
      authentication: "oauth2"
      actions:
        - "create_record"
        - "update_record"
        - "list_records"
        - "create_table"
      
    mongodb:
      name: "MongoDB"
      description: "Database operations"
      authentication: "connection_string"
      actions:
        - "insert_document"
        - "find_documents"
        - "update_document"
        - "delete_document"
      
    postgresql:
      name: "PostgreSQL"
      description: "Database queries"
      authentication: "connection_string"
      actions:
        - "execute_query"
        - "create_table"
        - "insert_data"
        - "select_data"

  research_academic:
    zotero:
      name: "Zotero"
      description: "Reference management"
      authentication: "api_key"
      actions:
        - "add_item"
        - "create_collection"
        - "search_library"
        - "export_citations"
      
    mendeley:
      name: "Mendeley"
      description: "Research collaboration"
      authentication: "oauth2"
      actions:
        - "add_document"
        - "create_group"
        - "share_document"
        - "search_papers"
      
    orcid:
      name: "ORCID"
      description: "Researcher identification"
      authentication: "oauth2"
      actions:
        - "get_profile"
        - "update_works"
        - "search_researchers"
        - "create_work"
      
    researchgate:
      name: "ResearchGate"
      description: "Academic networking"
      authentication: "oauth2"
      actions:
        - "get_profile"
        - "search_papers"
        - "follow_researcher"
        - "share_publication"

# Action Configuration
actions:
  email:
    send_email:
      description: "Send email with optional attachments"
      required_fields: ["to_email", "subject", "body"]
      optional_fields: ["cc_emails", "bcc_emails", "attachments", "is_html"]
      
    list_messages:
      description: "Retrieve and filter email messages"
      required_fields: []
      optional_fields: ["folder", "max_results", "is_read", "subject", "from_address"]
      
    reply_to_email:
      description: "Reply to a specific email message"
      required_fields: ["message_id", "comment"]
      optional_fields: ["cc_emails", "bcc_emails"]

  calendar:
    create_event:
      description: "Create a calendar event"
      required_fields: ["subject", "start_datetime", "end_datetime"]
      optional_fields: ["body", "attendees", "location", "is_online_meeting"]
      
    list_events:
      description: "Retrieve calendar events"
      required_fields: []
      optional_fields: ["max_results", "filter", "timezone", "orderby"]
      
    get_event:
      description: "Get specific event details"
      required_fields: ["event_id"]
      optional_fields: []

  file_management:
    upload_file:
      description: "Upload file to cloud storage"
      required_fields: ["file_path", "file_name"]
      optional_fields: ["folder_path", "description", "tags"]
      
    download_file:
      description: "Download file from cloud storage"
      required_fields: ["file_id"]
      optional_fields: ["local_path"]
      
    list_files:
      description: "List files in storage"
      required_fields: []
      optional_fields: ["folder_path", "file_type", "max_results"]

# Error Handling
error_handling:
  retry_attempts: 3
  retry_delay: 1.0  # seconds
  timeout: 60.0  # seconds
  
  # Error messages
  messages:
    authentication_failed: "Authentication failed. Please check your credentials."
    action_failed: "Action execution failed. Please check parameters and permissions."
    rate_limit_exceeded: "Rate limit exceeded. Please try again later."
    service_unavailable: "Service is temporarily unavailable."
    invalid_parameters: "Invalid parameters provided for the action."
    permission_denied: "Insufficient permissions for this action."

# Performance Optimization
performance:
  batch_operations: true
  max_batch_size: 100
  request_delay: 0.1  # seconds between requests
  cache_enabled: false
  cache_duration: 3600  # seconds
  
# Security
security:
  api_key_validation: true
  oauth_validation: true
  input_sanitization: true
  output_filtering: true
  rate_limiting: true
  max_requests_per_minute: 60

# Monitoring
monitoring:
  log_level: "info"
  log_requests: true
  log_responses: false
  metrics_enabled: true
  alert_on_errors: true
